import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Trash2 } from 'lucide-react';
import api from '../services/api';

export default function DossierList() {
    const navigate = useNavigate();
    const [dossiers, setDossiers] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [deletingId, setDeletingId] = useState<string | null>(null);

    useEffect(() => {
        const fetchDossiers = async () => {
            try {
                const response = await api.get('/dossiers');
                // Handle both array response and object with data property
                const data = response.data;
                if (Array.isArray(data)) {
                    setDossiers(data);
                } else if (data && Array.isArray(data.data)) {
                    setDossiers(data.data);
                } else {
                    console.warn('Unexpected dossiers response format:', data);
                    setDossiers([]);
                }
            } catch (error) {
                console.error('Failed to fetch dossiers', error);
                setDossiers([]);
            } finally {
                setLoading(false);
            }
        };
        fetchDossiers();
    }, []);

    const handleDelete = async (id: string, subject: string) => {
        if (!confirm(`Are you sure you want to delete the dossier for "${subject}"? This action cannot be undone.`)) {
            return;
        }

        setDeletingId(id);
        try {
            await api.delete(`/dossiers/${id}`);
            setDossiers(dossiers.filter(d => d.id !== id));
        } catch (error) {
            console.error('Failed to delete dossier', error);
            alert('Failed to delete dossier. Please try again.');
        } finally {
            setDeletingId(null);
        }
    };

    if (loading) return <div className="p-8 text-center text-muted">Loading Dossiers...</div>;

    return (
        <div className="dossier-list-page">
            <h2 className="page-title">Intelligence Dossiers</h2>
            <p className="page-subtitle">Historical intelligence reports generated by the Aegis system.</p>

            <div className="glass-card overflow-hidden">
                <table className="dossier-table">
                    <thead>
                        <tr>
                            <th>Target Subject</th>
                            <th>Status</th>
                            <th>Risk Level</th>
                            <th>Generated At</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {dossiers.length === 0 ? (
                            <tr>
                                <td colSpan={5} className="text-center p-8 text-muted">No dossiers found. Start a deep search to generate one.</td>
                            </tr>
                        ) : (
                            dossiers.map(d => (
                                <tr key={d.id}>
                                    <td className="subject-cell font-bold">{d.subject}</td>
                                    <td>
                                        <span className="badge badge-success">COMPLETED</span>
                                    </td>
                                    <td>
                                        <span className={`risk-tag risk-${(d.content?.riskAssessment?.riskLevel || 'unknown').toLowerCase()}`}>
                                            {d.content?.riskAssessment?.riskLevel || 'N/A'}
                                        </span>
                                    </td>
                                    <td>{new Date(d.createdAt).toLocaleString()}</td>
                                    <td>
                                        <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                                            <button className="view-btn" onClick={() => navigate(`/dossiers/${d.id}`)}>
                                                View Intelligence
                                            </button>
                                            <button
                                                className="delete-btn"
                                                onClick={() => handleDelete(d.id, d.subject)}
                                                disabled={deletingId === d.id}
                                                style={{
                                                    padding: '6px 12px',
                                                    background: deletingId === d.id ? 'var(--glass-border)' : 'rgba(239, 68, 68, 0.2)',
                                                    color: deletingId === d.id ? 'var(--text-muted)' : '#ef4444',
                                                    border: '1px solid rgba(239, 68, 68, 0.3)',
                                                    borderRadius: '6px',
                                                    cursor: deletingId === d.id ? 'not-allowed' : 'pointer',
                                                    display: 'flex',
                                                    alignItems: 'center',
                                                    gap: '6px',
                                                    fontSize: '13px',
                                                    transition: 'all 0.2s ease',
                                                }}
                                                onMouseEnter={(e) => {
                                                    if (deletingId !== d.id) {
                                                        e.currentTarget.style.background = 'rgba(239, 68, 68, 0.3)';
                                                    }
                                                }}
                                                onMouseLeave={(e) => {
                                                    if (deletingId !== d.id) {
                                                        e.currentTarget.style.background = 'rgba(239, 68, 68, 0.2)';
                                                    }
                                                }}
                                            >
                                                <Trash2 size={14} />
                                                {deletingId === d.id ? 'Deleting...' : 'Delete'}
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
}
